
language: ruby
rvm:
- 2.1.1
branches:
  only:
    - master

services:
  - redis-server
  - mongodb
  - postgresql

addons:
  postgresql: "9.2"

env:
  DB_USER: postgres
  RAILS_ENV: integration
  global:
    - S3_REGION="us-east-1"
    - S3_BUCKET_NAME="io.bixby.gemcache.wad.integration"
    - secure: "fzS/duAKlE/3vYxYYEAjfbBfN/8qHbrSfKyoh1iOyGr8Pp6VKXtj0DwcyByr8QRsBDz/3Eay9svWb80k5z7eMyyfyNL29c0/EcMYkLIxPkDpoEa1rWMeiI0ts0/Eq2eu+Vn9Ljr33NzOAqpAUHUVbaOY6dYffBeJRd61c1fl71w="

before_install:
  - "curl -sL https://s3.bixby.io/wad > ~/wad"
  - "chmod +x ~/wad"

install:
  - "scripts/setup_travis.sh"

before_script:
  - "psql -c 'create database bixby' -U postgres"

script: "scripts/travis_ci.sh"
