
source "https://rubygems.org"

group :development do
    # bixby gems
    gem "api-auth", :github => "chetan/api_auth", :branch => "bixby"
    gem "bixby-common", :path => "../src/common"
    gem "bixby-client", :path => "../src/client"

    # test tools (frameworks, mock, runners, etc)
    gem 'rake-hooks', :require => false

    # test utils
    gem "easycov", :github => "chetan/easycov"
    gem "micron", :github => "chetan/micron"
    gem "test_guard", :git => "https://github.com/chetan/test_guard.git"

    # misc
    gem "awesome_print"
    gem "pry"
    gem "yard"
end
