# encoding: utf-8

ROOT_PATH = File.expand_path('..', __FILE__)

ENV["RAILS_ENV"] = "integration"
ENV["BUNDLE_GEMFILE"] = File.join(ROOT_PATH, "Gemfile")

require 'rake'

Dir['lib/tasks/**/*.rake'].each { |rake| load rake }

require "micron/rake"
Micron::Rake.new do |task|
end
task :default => :test
